sudo: true

env:
  global:
    - DOCKER_CACHE_DIR=$HOME/.cache/docker
    - DOCKER_API_CACHE=$CACHE_DIR/${TRAVIS_BRANCH}

branches:
  only:
    - master
    - develop
    - staging

cache:
  bundler: true
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - stage: test
      before_script:
        - chmod +x ./scripts/phpunit-tests.sh
      name: "Run PHPUnit Tests"
      language: php
      php:
        - '7.2'
      script:
        - ./scripts/phpunit-tests.sh

    - stage: build docker image
      name: "Build and Deploy Docker Image"
      before_install:
        - if [ -f ${DOCKER_API_CACHE} ]; then gunzip -c ${DOCKER_API_CACHE} | docker load; fi
      install:
        - if [ ! -f ${DOCKER_API_CACHE} ]; then docker save 7otk/commy_api:{$TRAVIS_BRANCH} | gzip > ${DOCKER_API_CACHE}; fi
      before_script:
        - chmod +x ./scripts/docker-build-push.sh
      services: docker
      script:
        - ./scripts/docker-build-push.sh
