sudo: true

env:
  global:
    - DOCKER_CACHE_DIR=$HOME/.cache/docker
    - DOCKER_API_CACHE=$CACHE_DIR/${TRAVIS_BRANCH}

branches:
  only:
    - master
    - develop
    - staging

cache:
  bundler: true
  directories:
    - $HOME/.composer/cache/files
    - $DOCKER_CACHE_DIR
    - $DOCKER_API_CACHE

jobs:
  include:
    - stage: test
      before_script:
        - chmod +x ./scripts/phpunit-tests.sh
      name: "Run PHPUnit Tests"
      script:
        - ./scripts/phpunit-tests.sh

    - stage: build docker image
      services: docker
      name: "Build and Deploy Docker Image"
      before_install:
        - if [ -f ${DOCKER_API_CACHE} ]; then sudo gunzip -c ${DOCKER_API_CACHE} | sudo docker load; fi
      install:
        - if [ ! -f ${DOCKER_API_CACHE} ]; then sdudo docker save 7otk/commy_api:{$TRAVIS_BRANCH} | sudo gzip > ${DOCKER_API_CACHE}; fi
      before_script:
        - chmod +x ./scripts/docker-build-push.sh
      script:
        - ./scripts/docker-build-push.sh
