sudo: true

branches:
  only:
    - master
    - develop
    - staging

cache:
  bundler: true
  directories:
    - $HOME/.composer/cache/files

before_script:
  - chmod +x ./scripts/docker-build-push.sh
  - chmod +x ./scripts/phpunit-tests.sh

jobs:
  include:
    - stage: test
      name: "Run PHPUnit Tests"
      language: php
      php:
        - '7.2'
      script:
        - ./scripts/phpunit-tests.sh

    - stage: build docker image
      name: "Build and Deploy Docker Image"
      services: docker
      script:
        - ./scripts/docker-build-push.sh
