sudo: true

language: php

env:
  - IMAGE_NAME=7otk/commy-api

php:
  - '7.2'

services:
  - docker

before_install:
  - echo "Login to Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "Logged into Docker Hub"

before_script:
  - composer install --no-interaction --no-ansi --optimize-autoloader --ignore-platform-reqs

jobs:
  include:
    - stage: test
      script:
        - phpunit

    - stage: build and deploy new docker image
      script:
        - ./script/docker-build-push
