sudo: true

language: php

env:
  - IMAGE_NAME=7otk/commy-api

php:
  - '7.2'

services:
  - docker

before_script:
 - chmod +x ./scripts/docker-build-push.sh
 - chmod +x ./scripts/phpunit-tests.sh

jobs:
  include:
    - stage: test
      script:
        - ./scripts/phpunit-tests.sh

    - stage: build and deploy new docker image
      script:
        - ./scripts/docker-build-push.sh
